### ISSUE TITLE
pantilthat 0.0.7 in pip fails.

### ISSUE THREAD

**Issue by e270889o** [pimoroni/pantilt-hat#22]
Hi.

I've tried to install pantilthat 0.0.7 from pip inside a virtual env. It installs but you cannot use it since it gives you an error at import.

The problem is that your library uses smbus, but there is no smbus for pip, so it wont work in virtual envs.

The solution is to replace the use of smbus for smbus2 in your library (all references)

Maybe you can use this library instead since its more common everyday to use virtual envs with pip.

**Comment by Gadgetoid** [comment]
The underlying PanTilt HAT class can support any smbus-compatible library:

https://github.com/pimoroni/pantilt-hat/blob/543c92852fa227fffc0768599a00e47de28a3e33/library/pantilthat/pantilt.py#L69-L77

But you're right- since it's set up for you in `__init__.py` you don't get the opportunity to call the class constructor with an alternate library.
